name: docker
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull and Up docker image on cloud server
        uses: appleboy/ssh-action@master
        with:
          host: iris-agent.cloud.banksia.global
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin;
            sudo docker-compose pull;
            sudo docker-compose up -d;
            sudo docker system prune -f;
            sleep 20;
            sudo docker exec ubuntu_iris_1 iris session iris -U USER "##class(Ens.Config.Credentials).SetCredential(\"ApiKey\",\"ApiKey\",\"${{ secrets.API_KEY }}\",1)"  
            sudo docker exec ubuntu_iris_1 iris session iris -U USER "##class(Ens.Config.Credentials).SetCredential(\"lifx\",\"${{ secrets.LIFX }}\",\"\",1)"  